[package]
name = "tiny-wasm-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
nom = "7.1.3"
nom-leb128 = "0.2.0"
num-derive = "0.4.2"
num-traits = "0.2.19"

[dev-dependencies]
pretty_assertions = "1.4.0"
wat = "1.207.0"
